### ISSUE TITLE
cannot compile it

### ISSUE THREAD

**Issue by dariosalvi78** [mattybrad/drumkid#4]
after fixing the few issues, I get this:

Arduino: 1.8.12 (Mac OS X), Board: "Arduino Uno"

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/aj6373/Library/Arduino15/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/aj6373/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/aj6373/Documents/Arduino/libraries -fqbn=arduino:avr:uno -vid-pid=0403_6001 -ide-version=10812 -build-path /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608 -warnings=all -build-cache /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_cache_617705 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs=runtime.tools.avr-gcc.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5 -prefs=runtime.tools.arduinoOTA.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -verbose /Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/aj6373/Library/Arduino15/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/aj6373/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/aj6373/Documents/Arduino/libraries -fqbn=arduino:avr:uno -vid-pid=0403_6001 -ide-version=10812 -build-path /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608 -warnings=all -build-cache /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_cache_617705 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 -prefs=runtime.tools.avr-gcc.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5 -prefs=runtime.tools.arduinoOTA.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=/Users/aj6373/Library/Arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -verbose /Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino
Using board 'uno' from platform in folder: /Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2
Using core 'arduino' from platform in folder: /Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2
Detecting libraries used...
/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/cores/arduino -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/variants/standard /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/drumkid.ino.cpp -o /dev/null
Alternatives for Bounce2.h: [Bounce2@2.53]
ResolveLibrary(Bounce2.h)
  -> candidates: [Bounce2@2.53]
/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/cores/arduino -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/variants/standard -I/Users/aj6373/Documents/Arduino/libraries/Bounce2/src /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/drumkid.ino.cpp -o /dev/null
Alternatives for EEPROM.h: [EEPROM@2.0]
ResolveLibrary(EEPROM.h)
  -> candidates: [EEPROM@2.0]
/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/cores/arduino -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/variants/standard -I/Users/aj6373/Documents/Arduino/libraries/Bounce2/src -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/libraries/EEPROM/src /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/drumkid.ino.cpp -o /dev/null
Using cached library dependencies for file: /Users/aj6373/Documents/Arduino/libraries/Bounce2/src/Bounce2.cpp
Generating function prototypes...
/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/cores/arduino -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/variants/standard -I/Users/aj6373/Documents/Arduino/libraries/Bounce2/src -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/libraries/EEPROM/src /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/drumkid.ino.cpp -o /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/preproc/ctags_target_for_gcc_minus_e.cpp
/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/preproc/ctags_target_for_gcc_minus_e.cpp
Compiling sketch...
/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/bin/avr-g++ -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/cores/arduino -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/variants/standard -I/Users/aj6373/Documents/Arduino/libraries/Bounce2/src -I/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/libraries/EEPROM/src /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/drumkid.ino.cpp -o /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/drumkid.ino.cpp.o
In file included from /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:23:0,
                 from /Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:18:
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if !(IS_AVR() || IS_TEENSY3() || IS_STM32() || IS_ESP8266() || IS_SAMD21())
              ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:30: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if !(IS_AVR() || IS_TEENSY3() || IS_STM32() || IS_ESP8266() || IS_SAMD21())
                              ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:30: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:30: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:30: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:30: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:44: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if !(IS_AVR() || IS_TEENSY3() || IS_STM32() || IS_ESP8266() || IS_SAMD21())
                                            ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:44: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:44: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:44: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:44: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:44: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:44: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:60: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if !(IS_AVR() || IS_TEENSY3() || IS_STM32() || IS_ESP8266() || IS_SAMD21())
                                                            ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:21:75: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if !(IS_AVR() || IS_TEENSY3() || IS_STM32() || IS_ESP8266() || IS_SAMD21())
                                                                           ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:26:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if IS_STM32()
              ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:26:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:26:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:26:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:26:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:26:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:26:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/hardware_defines.h:28:18: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #elif IS_ESP8266()
                  ^
In file included from /Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:18:0:
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:25:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if IS_TEENSY3()
                ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:25:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:25:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:25:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:25:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
In file included from /Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:18:0:
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:181:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if IS_TEENSY3()
                ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:181:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:181:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:181:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:181:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:183:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #elif IS_STM32()
                ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:183:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:183:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:183:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:183:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:183:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:183:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:185:18: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #elif IS_ESP8266()
                  ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:187:17: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #elif IS_SAMD21()
                 ^
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:189:14: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #elif IS_AVR()
              ^
In file included from /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/Sample.h:19:0,
                 from /Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:19:
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/mozzi_pgmspace.h:9:16: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if IS_ESP8266()
                ^
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:62:0: warning: "CONTROL_RATE" redefined
 #define CONTROL_RATE 256 // tweak this value if performance is bad, must be power of 2 (64, 128, etc)
 
In file included from /Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:18:0:
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/MozziGuts.h:46:0: note: this is the location of the previous definition
 #define CONTROL_RATE 64
 
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino: In function 'void scheduleNote(byte, byte, byte, float)':
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:317:44: warning: unused parameter 'beatNumber' [-Wunused-parameter]
 void scheduleNote(byte channelNumber, byte beatNumber, byte velocity, float delayTime) {
                                            ^~~~~~~~~~
In file included from /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/drumkid.ino.cpp:1:0:
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino: In function 'void scheduler()':
/Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/cores/arduino/Arduino.h:95:39: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 #define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
                                  ~~~~~^~~~~~
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:339:20: note: in expansion of macro 'constrain'
     byte stepLED = constrain(thisStep, 0, 4);
                    ^~~~~~~~~
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino: In function 'void updateControl()':
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:517:12: warning: unused variable 'dummyReading' [-Wunused-variable]
       byte dummyReading = mozziAnalogRead(breadboardAnalogPins[i]);
            ^~~~~~~~~~~~
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino: In function 'void triggerNote(byte, byte)':
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:707:31: warning: unused parameter 'vel' [-Wunused-parameter]
 void triggerNote(byte i, byte vel) {
                               ^~~
In file included from /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/Sample.h:19:0,
                 from /Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:19:
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/mozzi_pgmspace.h: In instantiation of 'bool mozzi_is_const_pointer(const T*) [with T = signed char]':
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/mozzi_pgmspace.h:47:30:   required from 'T FLASH_OR_RAM_READ(T*) [with T = const signed char]'
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/Sample.h:181:41:   required from 'int8_t Sample<NUM_TABLE_CELLS, UPDATE_RATE, INTERP>::next() [with unsigned int NUM_TABLE_CELLS = 7581; unsigned int UPDATE_RATE = 16384; unsigned char INTERP = 0; int8_t = signed char]'
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:232:15:   required from here
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/MozziDK/mozzi_pgmspace.h:18:66: warning: unused parameter 'x' [-Wunused-parameter]
 template<typename T> inline bool mozzi_is_const_pointer(const T* x) { return true; }
                                                                  ^
Compiling libraries...
Compiling library "Bounce2"
Using previously compiled file: /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/libraries/Bounce2/Bounce2.cpp.o
Compiling library "EEPROM"
Compiling core...
Using precompiled core: /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_cache_617705/core/core_arduino_avr_uno_5a0ad971788a2cbbb26baa7ffbb7a50f.a
Linking everything together...
/Users/aj6373/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/bin/avr-gcc -Wall -Wextra -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/drumkid.ino.elf /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/sketch/drumkid.ino.cpp.o /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/libraries/Bounce2/Bounce2.cpp.o /var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608/../arduino_cache_617705/core/core_arduino_avr_uno_5a0ad971788a2cbbb26baa7ffbb7a50f.a -L/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T/arduino_build_52608 -lm
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T//ccfHMTYf.ltrans0.ltrans.o: In function `setup':
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:201: undefined reference to `startMozzi(int)'
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:202: undefined reference to `randSeed()'
/var/folders/zr/lyn3n_j97zl69b3z7ngd94h1z2gtmf/T//ccfHMTYf.ltrans0.ltrans.o: In function `loop':
/Users/aj6373/Downloads/drumkid-master/v4/arduino/drumkid/drumkid.ino:264: undefined reference to `audioHook()'
collect2: error: ld returned 1 exit status
Using library Bounce2 at version 2.53 in folder: /Users/aj6373/Documents/Arduino/libraries/Bounce2 
Using library EEPROM at version 2.0 in folder: /Users/aj6373/Library/Arduino15/packages/arduino/hardware/avr/1.8.2/libraries/EEPROM 
exit status 1
Error compiling for board Arduino Uno.

**Comment by dariosalvi78** [comment]
OK, also this was fixed by importing Mozzi (latest release). It compiles at least!

**Comment by dariosalvi78** [comment]
after compiling it, it runs, but I can't hear anything interesting. It emits sounds, and they look rhythmic, but nothing that resembles what you show in the video. BTW, I am trying this on an Arduino UNO and a breadboard, using the schema described in this repo (v4).

I'll do some more tests and see. It would be really nice to replicate this: my aim was to build it for my daughter so that she can learn some electronic music.

All the best.

**Comment by mattybrad** [comment]
Hey Dario, really sorry I only just saw your issues - I've never had a GitHub repo that people actually interacted with before so I hadn't set up any notifications! I've done lots of updates since this - hopefully you might have better luck now :)

**Comment by dariosalvi78** [comment]
thanks Matt. I'll try it and see if I can make it work.
